### ISSUE TITLE
Change API front page title and main heading to Linked Events Helsinki

### ISSUE THREAD

**Issue by aleksisalonen** [City-of-Helsinki/linkedevents#196]
Change API front page main header (.page-header h1) and page title from "Linked Events" to "Linked Events Helsinki". Separate Linked Events API-instances should be easy to differentiate .

http://api.hel.fi/linkedevents/v1/

**Comment by Rikuoja** [comment]
The root page title comes from events code, not the helevents part that customizes the header, info box etc. for Helsinki purposes.

To be investigated how to change the title outside events code, because we want the events code to be reusable in all cities. It should not contain any references to Helsinki.

**Comment by aleksisalonen** [comment]
That's right, it would have been too easy otherwise. Finding a solution will however help other LE-instances as well.

While we're at it, let's change the blue band text "HKI Linked Events API v1" to "Helsinki Linked Events API v1".
